[mypy]
# Set the Python version constraint match the project.
python_version = 3.13

# Configure general settings.
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True

# Follow imports to check consistency.
follow_imports = normal

# Show error codes.
show_error_codes = True

# Ignore third-party libraries without type stubs.
[mypy-numba.*]
ignore_missing_imports = True
[mypy-tqdm.*]
ignore_missing_imports = True
[mypy-pyvista.*]
ignore_missing_imports = True
[mypy-webp.*]
ignore_missing_imports = True
