[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.black]
target-version = ['py311', 'py312', 'py313', 'py314']
include = '\.pyi?$'

[tool.codespell]
ignore-words = ".codespell-ignore.txt"
skip = "docs/_build/*,*.dat"

[tool.coverage.run]
source = ["pterasoftware"]

[tool.docformatter]
black = true
recursive = true
force-wrap = true

[tool.octowrap]
line-length = 88
recursive = true
inline = true
list-wrap = true
diff-only = false
diff-base = "HEAD"
todo-case-sensitive = true
todo-multiline = true
extend-exclude = ["private", ".venv-wsl", "experimental"]
todo-patterns = ["TODO:", "FIXME:"]
extend-todo-patterns = ["TEST:"]
