"""Contains the movement classes."""

import pterasoftware.movements.aeroelastic_airplane_movement
import pterasoftware.movements.aeroelastic_movement
import pterasoftware.movements.aeroelastic_wing_cross_section_movement
import pterasoftware.movements.aeroelastic_wing_movement
import pterasoftware.movements.airplane_movement
import pterasoftware.movements.free_flight_movement
import pterasoftware.movements.free_flight_operating_point_movement
import pterasoftware.movements.movement
import pterasoftware.movements.operating_point_movement
import pterasoftware.movements.wing_cross_section_movement
import pterasoftware.movements.wing_movement
