name: Format and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.3
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ci.txt
    - name: Run tests
      run: |
        coverage run --source=pterasoftware -m unittest discover -s tests
        codecov
        black pterasoftware