name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ci.txt
    - name: Format with Black
      run: |
        black pterasoftware
    - name: Run tests with Coverage
      run: |
        coverage run --source=pterasoftware -m unittest discover -s tests
        codecov
