name: isort

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 # v1
