name: Test package

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup a headless display
      run: |
        git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
        source ./gl-ci-helpers/travis/setup_headless_display.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ci.txt
    - name: Test
      run: |
        coverage run --source=pterasoftware -m unittest discover -s tests
        codecov